// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ProjectMFR;

{ITE} {DFMFileType} {MainUnit.dfm}
{ITE} {RCFileType} {Win32\Debug\ProjectMFR_DRC.rc}

{$R 'MainUnit.dfm' Form1:TForm}
{$R 'Win32\Debug\ProjectMFR_DRC.res' 'Win32\Debug\ProjectMFR_DRC.rc'}

{$E RUS}

begin
end.
